name: Build_and_Publish

on:
  push:
    branches:
      # - dev
      - master  # Добавьте эту строку, если хотите публиковать и при пуше в master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install env
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade poetry
          poetry self update
          pip install virtualenv filelock
          poetry config virtualenvs.create true

      - name: Install dependencies
        run: poetry install

      - name: Publish
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          rm -rf dist/
          poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }} --no-interaction